services:
  app:
      image: gotodoo
      build:
        context: .
        args:
          target: dev
      environment:
        TODO_ENV: dev
        PORT: 8080
      volumes:
        - .:/app

      ports:
        - "18000:8080"