root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"

full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"

include_ext = ["go", "tp1", "tmp1", "html"]

include_dir = []
exclude_dir = ["assets", 'tmp", "vendor", "frontend/node_modules", "_tools", "cert", "testutil"]

exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true


log = "air.log"
delay = 1000

stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
builder = "tellow"
rummer = "green"

[misc]
clean_on_exit = true